### ISSUE TITLE
NodeJS version requirement

### ISSUE THREAD

**Issue by Cyberrebell** [WindomZ/swagger-merger#15]
I'm not a JS expert but in your package.json you require:
```
"engines": {
    "node": ">= 0.6.x"
}
```

I'm using Debian Stretch with default node version: v4.8.2 (which has no full ES6 Support) but you seem to use ES6 features in this project.

You should fix the required version in package.json to give everyone who uses an outdated version of node a hint why he can't install swagger-merger and avoid that he is getting an error like this:

```
/usr/local/lib/node_modules/swagger-merger/node_modules/fmtconv/lib/converter.js:19
function fmtconv (input, output, compact = false) {
                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/swagger-merger/node_modules/fmtconv/lib/fmtconv.js:6:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I think at least v6.0.0 should be required.

**Comment by WindomZ** [comment]
First, thanks for your issue, this problem is my negligence.
I will fix this problem as soon as possible.

Here, I have a recommendation, it can help you manage multiple active node.js versions: [creationix/nvm](https://github.com/creationix/nvm)
