### ISSUE TITLE
debug not working properly

### ISSUE THREAD

**Issue by ivan-gomez-shapestone** [WindomZ/swagger-merger#57]
I'm trying to run a shell script to build a documentation. When I do this I get an error: 

xxxxxxxx/node_modules/swagger-merger/bin/swagger-merger.js:27
      input: options.input || file || '',
                     ^

TypeError: Cannot read property 'input' of undefined
    at Command.program.version.usage.description.option.option.option.option.action (/xxxxxxxxxx/node_modules/swagger-merger/bin/swagger-merger.js:27:22)
    at Command.listener (/xxxxxxxxx/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/xxxxxxxxxxx/node_modules/commander/index.js:668:12)
    at Command.parse (/xxxxxxxxxxxxx/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/xxxxxxxxxxxxxx/node_modules/swagger-merger/bin/swagger-merger.js:35:9)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

If I run the command separately I get:
swagger-merger --debug -i src/swagger/main.yml
Unexpected token [ in JSON at position 3502

what it's not very helpful without the proccessed file. i have like 200

node: 11.3.0
npm: 6.4.1

Thanks in advance

**Comment by WindomZ** [comment]
This was the old code: `input: options.input || file || '',`

You can try to update to the latest version.

Thanks for your feedback:)

**Comment by ivan-gomez-shapestone** [comment]
Thanks for taking the time to answer.

i'm suppose to have the latest version:
swagger-merger -V
1.4.3

Apart from:  input: options.input || file || '',

Is there a way that --debug tell me the file where the error is?

Thanks
